### ISSUE TITLE
vagrant plugin install vagrant-libvirt produces error: conflicting dependencies net-ssh (>= 2.6.5) and net-ssh (= 6.2.0.rc1)

### ISSUE THREAD

**Issue by mb720** [vagrant-libvirt/vagrant-libvirt#1210]
Hi and thanks for vagrant-libvirt!

I've installed Vagrant on Arch Linux 5.10.13 using `sudo pacman -Sy vagrant`.

I'm trying to build a metasploitable image that can be run using QEMU/KVM. Thinking it was an issue with metasploitable, I wrote a bug report [there](https://github.com/rapid7/metasploitable3/issues/509) but their developers sent me here.

Reading [here](https://stackoverflow.com/questions/42155213/using-vagrant-to-set-up-a-vm-with-kvm-qemu-without-virtualbox#46037150) that I need to install the vagrant-libvirt plugin, I tried so using `vagrant plugin install vagrant-libvirt`. This produces an error though:

      conflicting dependencies net-ssh (>= 2.6.5) and net-ssh (= 6.2.0.rc1)
        Activated net-ssh-6.2.0.rc1
        which does not match conflicting dependency (>= 2.6.5)

        Conflicting dependency chains:
          net-ssh (= 6.2.0.rc1), 6.2.0.rc1 activated

        versus:
          net-scp (= 1.2.1), 1.2.1 activated, depends on
          net-ssh (>= 2.6.5)

        Gems matching net-ssh (>= 2.6.5):
          net-ssh-6.2.0.rc1

Is there a way to fix this?

## Host System
* OS: Arch Linux 5.10.13
* Vagrant version: 2.2.14
* `vagrant plugin list`: No plugins installed.
* libvirt version: 7.0.0

**Comment by electrofelix** [comment]
@mb720 this looks like it's most likely some issue with vagrant itself, as vagrant-libvirt doesn't have a direct dependency on a specific version of net-ssh, and is instead using it through vagrant. We do use fog-libvirt, but that doesn't care about what version, just as long as it's installed:
```
fog-libvirt-0.7.0.gemspec:    s.add_dependency(%q<net-ssh>.freeze, [">= 0"])
```

When I grep'ed my local vagrant install, the only mention I see of the versions `2.6.5` it is under /opt/vagrant/ indicating that both of these versions:
```
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/vagrant.gemspec:  s.add_dependency "net-ssh", ">= 6.2.0.rc1", "< 7"
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/templates/locales/en.yml:        If the problem persists, please report a bug to the net-ssh project.
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/CHANGELOG.md:- core: Update to net-ssh to 6.0 and net-sftp to 3.0 [GH-11621]
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/CHANGELOG.md:- core: Update net-ssh dependency constraint to ~> 5.0.0 [GH-10066]
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/CHANGELOG.md:  - Using newer versions of net-ssh and net-scp. [GH-1436]
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/CHANGELOG.md:  - Internal SSH through net-ssh now uses `IdentitiesOnly` thanks to
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/CHANGELOG.md:    upstream net-ssh fix.
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/plugins/communicators/ssh/plugin.rb:      net-ssh library.
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/plugins/kernel_v2/config/ssh_connect.rb:        # Values for verify_host_key changed in 5.0.0 of net-ssh. If old value
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/Gemfile.lock:      net-ssh (~> 5.2.0)
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/Gemfile.lock:      net-ssh (>= 2.6.5)
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/Gemfile.lock:      net-ssh (>= 2.6.5)
/opt/vagrant/embedded/gems/2.2.13/gems/vagrant-2.2.13/Gemfile.lock:    net-ssh (5.2.0)
```

It's suggested in https://github.com/hashicorp/vagrant/issues/8948 and https://github.com/hashicorp/vagrant/issues/9388 that there is some issue within vagrant that can be resolved by running an uninstall script from the installer, but I wouldn't have thought that should be necessary with a distro provided package. Perhaps there are some stray files under ~/.vagrant.d of the user you are running vagrant as from a previous installation?

Not exactly sure where else to suggest looking, but as the plugin install is handled by vagrant itself, and the dependency versions mentioned above are coming from it, it looks like it's further down the rabbit hole.

**Comment by mb720** [comment]
Thanks for the pointers.

I uninstalled Vagrant with `pacman -Rns vagrant`, deleted the `~/.vagrant.d` dir and reinstalled Vagrant. But `vagrant plugin install vagrant-libvirt` produces the same error.

I just found [this recent issue](https://github.com/hashicorp/vagrant/issues/12202) pertaining to Arch Linux and derivatives.

Encouragingly, there is a [merged patch](https://github.com/hashicorp/vagrant/pull/12213) that is supposed to fix it.

**Comment by electrofelix** [comment]
@mb720 glad to see that the underlying issue is solved, the provider name in this case is `libvirt`, still use kvm under the hood (assuming available), just that we talk to it via the libvirt API.

So the command to run is `vagrant up --provider=libvirt`

**Comment by rekcus2** [comment]
@mb720 why did you close this issue when based on that you said it seems it is NOT fixed, you just installed an old version to fix it for yourself.

@mb720 what "underlying issue is solved"???

**Comment by mb720** [comment]
@rekcus2: I closed it because according to electrofelix, the issue lies with vagrant itself, not with vagrant-libvirt. I assume the "underlying issue" electrofelix is referring to, is [the issue that I linked to](https://github.com/hashicorp/vagrant/issues/12202) for which there is a patch.
